version: "3"

services:
    HostUser:
        image: handsonsecurity/seed-ubuntu:large
        container_name: hostUser-10.9.0.5
        tty: true
        cap_add:
                - ALL
        sysctls:
                - net.ipv4.ip_forward=1
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.5
        command: bash -c "
                      ip route add 192.168.60.0/24 via 10.9.0.11 &&
                      ip route add  12.9.0.0/24 via 10.9.0.11 &&
                      /etc/init.d/openbsd-inetd start  &&
                      tail -f /dev/null
                 "

    BannedWebsite:
        image: handsonsecurity/seed-ubuntu:large
        container_name: BannedWebsite-192.168.60.5
        tty: true
        cap_add:
                - ALL
        networks:
            net-192.168.60.0:
                ipv4_address: 192.168.60.5
        command: bash -c "
                      ip route del default  &&
                      ip route add default via 192.168.60.11  &&
                      /etc/init.d/openbsd-inetd start  &&
                      tail -f /dev/null
                 "
             
    VPN:
        image: handsonsecurity/seed-ubuntu:large
        container_name: VPN-12.9.0.5
        tty: true
        cap_add:
                - ALL
        sysctls:
                - net.ipv4.ip_forward=1
        networks:
            net-12.9.0.0:
                ipv4_address: 12.9.0.5
        command: bash -c "
                      ip route add  10.9.0.0/24 via 12.9.0.11 &&
                      ip route add  192.168.60.0/24 via 12.9.0.11 &&
                      /etc/init.d/openbsd-inetd start  &&
                      tail -f /dev/null
                      "

    Router:
        build: router
        image: seed-router-image
        container_name: seed-router
        tty: true
        cap_add:
                - ALL
        sysctls:
                - net.ipv4.ip_forward=1
        volumes:
                - ./volumes:/volumes

        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.11
            net-192.168.60.0:
                ipv4_address: 192.168.60.11
            net-12.9.0.0:
                ipv4_address: 12.9.0.11
        command: bash -c "
                      ip route del default  &&
                      ip route add default via 10.9.0.1 &&
                      iptables -A FORWARD -s 10.9.0.0/24 -d 192.168.60.0/24 -j DROP &&
                      /etc/init.d/openbsd-inetd start  &&
                      tail -f /dev/null
                 "

networks:
    net-192.168.60.0:
        name: net-192.168.60.0
        ipam:
            config:
                - subnet: 192.168.60.0/24
                
    net-12.9.0.0:
        name: net-12.9.0.0
        ipam:
            config:
                - subnet: 12.9.0.0/24

    net-10.9.0.0:
        name: net-10.9.0.0
        ipam:
            config:
                - subnet: 10.9.0.0/24

